[tool.poetry]
name = "freakble"
version = "0.1.0"
description = ""
authors = ["Daniele Tricoli <eriol@mornie.org>"]
readme = "README.md"
packages = [{include = "freakble", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ble-serial = "^2.7.0"
click = "^8.1.3"

[tool.poetry.scripts]
freakble = "freakble.main:run"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
